services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mike_admin:Mwa$$0152@db:5432/speedy_bites
      - TOKEN_SECRET=2c869fb64731f8582f3c0989f66675e0766324dcd9116e917d23d9a0d24e1236
      - MPESA_CONSUMER_KEY
      - MPESA_CONSUMER_SECRET
      - MPESA_SHORTCODE
      - MPESA_PASSKEY
      - MPESA_CALLBACK_BASE
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  db:
    image: postgres:15
    container_name: speedy-bites-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mike_admin
      POSTGRES_PASSWORD: Mwa$$0152
      POSTGRES_DB: speedy_bites
    ports:
      - "54813:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mike_admin"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
