version = 5.6.0
archive_dir = /etc/letsencrypt/archive/kukunisisi.co.ke
cert = /etc/letsencrypt/live/kukunisisi.co.ke/cert.pem
privkey = /etc/letsencrypt/live/kukunisisi.co.ke/privkey.pem
chain = /etc/letsencrypt/live/kukunisisi.co.ke/chain.pem
fullchain = /etc/letsencrypt/live/kukunisisi.co.ke/fullchain.pem
[renewalparams]
account = c395037cc10465096cbabd56d925daaf
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
kukunisisi.co.ke = /var/www/certbot
www.kukunisisi.co.ke = /var/www/certbot
